### ISSUE TITLE
Settings Model

### ISSUE THREAD

**Issue by chrisvidal** [mohsin/Text-With-Button-Widget#1]
Where do you put the handler function when you use the widget in a settings model?
in that case there is no controller involved.

thanks

**Comment by mohsin** [comment]
You would need to extend the SettingsController in order to achieve that.

**Comment by chrisvidal** [comment]
yes and do you know his name by any chance?
I am looking for it

**Comment by chrisvidal** [comment]
got it `System\Controllers\Settings` in case of anyone needs this later

**Comment by chrisvidal** [comment]
```php
\System\Controllers\Settings::extend(function($controller) {
            $controller->addDynamicMethod('onUpdateCustomerDescription', function() use ($controller) {
                trace_log('it works');
            });
        });
```

**Comment by mohsin** [comment]
@chrisvidal I would also recommend you to filter down the Settings controller to only your settings context object using something like:
```php
\System\Controllers\Settings::extend(function($controller) {
    $context = \System\Classes\SettingsManager::instance()->getContext();
    if ($context->owner === 'acme.plugin' && $context->itemCode === 'my_settings_item') {
        // Add Dynamic method here
    }
});
```

This is good practice since it ensures the dynamic method is added only to the settings item you're interested in and not all the pages that use the settings controller.
